Feature/jail time
mini-maxit/worker pull request #7
Opened 2024-11-13 20:32 UTC by Matios102

Worker - added worker structure to hold logger and conn for easier channel management and logging 

Utils - added CopyFile function 

Runner - added logger to the structure for proper logging 

Logger config - change from logrus to zap

Executor - new status codes, command restriction to jail the executable 

Cpp-executor - logging, adjusted execution to jail the executable 

Dockerfile - changes made for chroot creation 

Chroot_init_script.sh - creating chroot, downloading packages needed to run cpp executables

2024-11-17 13:36 UTC, HermanPlay requested changes
Please resolve the conflicts, and it can be merged

2025-02-06 21:53 UTC, HermanPlay requested changes
Please remove useless comments. Fix comments and we are good to go

2025-02-06 21:53 UTC, HermanPlay commented on executor/cpp_executor.go
> +	if runErr != nil {
Let's invert this condition to reduce code indendation

2025-02-06 21:53 UTC, HermanPlay commented on executor/cpp_executor.go
> +	e.logger.Infof("Command executed successfully [MsgID: %s]", messageID)
The message of logger is not consistent. Because status code can be ErSignalRecieved, then this will not reflect what happened. Lets change this to "Finished executing command with status code: %d..."

2025-02-06 21:53 UTC, HermanPlay commented on worker/solution.go
> +	requestUrl := fmt.Sprintf("http://host.docker.internal:8888/getSolutionPackage?taskID=%d&userID=%d&submissionNumber=%d", taskId, userId, submissionNumber)
what the 🐓, I think we should pass address of filestorage from config and env vars. Also you can use aliases, such as container name

2025-02-07 09:03 UTC, HermanPlay submitted a review, later dismissed
lgtm

2025-02-07 09:05 UTC, HermanPlay approved these changes

2025-02-09 02:17 UTC, HermanPlay commented on solution/solution.go
> +func (ss SolutionStatus) String() string {
I like it Picasso

2025-02-09 02:21 UTC, HermanPlay commented on tests/worker_test.go
> +	//this flag is very stupid but the linter does not allow me to unconditionally break the loop
If you no matter what read only the first element, then why don't you just `msgs[0]` it?

2025-02-09 02:23 UTC, HermanPlay commented on tests/worker_test.go
> +	err = deleteTask("1")
From my experience, you should avoid hardcoding values in tests. When something breaks and it will not be deleted your test will fail because of incorrect ID, you should consider using dynamic ID

2025-02-17 19:14 UTC, Matios102 commented on tests/worker_test.go
> +	err = deleteTask("1")
if something fails I delete this task in TestMain

2025-02-18 19:44 UTC, HermanPlay commented on run_tests.sh
> +sleep 15
it is better practice to implement polling plain sleep

2025-02-18 19:45 UTC, HermanPlay commented on solution/solution.go
> +	MemoryLimits     []int          // Memory limit for the
for the what?

2025-02-18 19:47 UTC, HermanPlay commented on tests/worker_test.go
> +	requestUrl := "http://file-storage:8888/createTask"
it is good practice to have config for test environment

2025-02-18 19:49 UTC, HermanPlay commented on utils/utils.go
>  func TarGzFolder(srcDir string) (string, error) {
bad naming and lack of documentation

2025-02-18 19:54 UTC, HermanPlay approved these changes

2025-02-20 13:37 UTC, merged